[pytest]
markers =
    invalid_posts_values: невалидные значения для payload Post
    invalid_posts: невалидные тесты - отсутствующие поля для Post
    invalid_get_item_400: невалидный item_id для Get получения объявления Bad Request
    invalid_get_item_404: невалидный item_id для Get получения объявления None Found
    invalid_get_item_statistics: невалидная проверка статистики объявления
    invalid_get_user_items: невалидный seller_id для Get все items
    valid_create_item_post: cоздание объявления
    valid_get_item_by_id: получаем объявление по item_id
    valid_get_items_by_user: получаем все объявления пользователя по user_id
    valid_get_item_statistics: получаем статистику объявления по item_id
    valid_post_any_value: малые и большие значения для POST
